In [1]:
import numpy as np

In [2]:
scores = [[ 316,  747, 4186,  220],
 [ 765,  930, None, None],
 [ 248,  171,   81,   92],
 [ 135,  132,   48,   88]]

In [3]:
times_matrix = np.full((4, 4), np.nan, dtype=np.float64)

In [4]:
times_matrix  # Fill

array([[nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])

In [5]:
#
# Vanilla subgroups
#
for i,  student_times in enumerate(scores):
    times_matrix[i, 0: len(student_times)] = student_times

In [6]:
times_matrix

array([[ 316.,  747., 4186.,  220.],
       [ 765.,  930.,   nan,   nan],
       [ 248.,  171.,   81.,   92.],
       [ 135.,  132.,   48.,   88.]])

In [7]:
#
# Median of subgroups
# https://docs.scipy.org/doc/numpy/reference/generated/numpy.nanmedian.html
# See:
# > Axis or axes along which the medians are computed. The default is to compute
# > the median along a flattened version of the array. A sequence of axes is
# > supported since version 1.9.0.
#
np.nanmedian(times_matrix)

195.5

In [8]:
# see how iterator behavior of this behaves in numpy
np.nanmedian([np.nanmedian(students_feedback_times) for students_feedback_times in np.nditer(times_matrix)])
# 195.5
np.nanmedian([np.nanmean(students_feedback_times) for students_feedback_times in np.nditer(times_matrix)])
# 195.5

/home/x/.local/share/virtualenvs/notebooks-3j7HZMtb/lib/python3.7/site-packages/numpy/lib/function_base.py:3405: RuntimeWarning: All-NaN slice encountered
  r = func(a, **kwargs)
/home/x/.local/share/virtualenvs/notebooks-3j7HZMtb/lib/python3.7/site-packages/ipykernel_launcher.py:4: RuntimeWarning: Mean of empty slice
  after removing the cwd from sys.path.


195.5

In [13]:
#
# Median of subgroups
#
median_matrix = np.full((4, 1), np.nan, dtype=np.float64)
for i,  student_times in enumerate(scores):
    median_matrix[i] = np.nanmedian(np.array(student_times, dtype=np.float64))

median_matrix

array([[531.5],
       [847.5],
       [131.5],
       [110. ]])

In [10]:
#
# Median of median of subgroups
#
np.nanmedian([np.nanmean(students_feedback_times) for students_feedback_times in np.nditer(median_matrix)])

331.5

In [11]:
#
# Average of subgroups
#
avg_matrix = np.full((4, 1), np.nan, dtype=np.float64)
for i,  student_times in enumerate(scores):
    avg_matrix[i] = np.nanmean(np.array(student_times, dtype=np.float64))

avg_matrix

array([[1367.25],
       [ 847.5 ],
       [ 148.  ],
       [ 100.75]])

In [12]:
#
# Median of average of subgroups
#
np.nanmedian([np.nanmean(students_feedback_times) for students_feedback_times in np.nditer(avg_matrix)])

497.75